refactor(RezervoClass): add bookingOpensAt and bookingClosesAt
mathiazom/rezervo-web pull request #74
Opened 2023-09-12 16:37 UTC by AdrianAndersen

We need this refactoring to so that we can use the time the booking opens to schedule the automatic booking

2023-09-12 21:20 UTC, mathiazom commented on src/lib/integrations/sit/adapters.ts
> +        bookingClosesAt: LocalizedDateTime.fromISO(startTime).minus({ minute: 5 }), // https://www.sit.no/content/trening-slik-booker-du
Hopefully this is equivalent :crossed_fingers:

2023-09-12 21:37 UTC, mathiazom commented
We need some Alembic migration here to support configurations using the old format (i.e. missing the `booking_opens_at`). Should be able to use the old technique of calculating booking time from class start time (at least for Sit, and I don't think we need to support FSC for this).

2023-09-12 21:48 UTC, mathiazom approved these changes

2023-09-18 08:25 UTC, mathiazom commented on src/components/configuration/ConfigBar.tsx
> +                    booking_opens_at: c.bookingOpensAt.toISO(),
I think `booking_opens_at` should be left out here, and that the booking scheduling should be performed on the backend. In the future, we might even move all this class config info to the backend and only submit a list of ids.

2023-09-18 08:26 UTC, mathiazom requested changes
Should not submit `booking_opens_at` to backend

2023-09-26 16:22 UTC, AdrianAndersen commented
We do not need this anymore, since we do not need to pass the integration nor the opening_time

2023-09-26 16:22 UTC, closed without merging